### ISSUE TITLE
Does not affect transitions to Exit.

### ISSUE THREAD

**Issue by NotAKidoS** [EtiTheSpirit/XansCVRTools#1]
Conversion script does not apply to Exit transitions.

I forgot exactly, but there's two or three transition types cause Unity is funny.

![image](https://user-images.githubusercontent.com/37721153/232196369-6534325a-0a22-4688-b338-b16bad1b35d6.png)

**Comment by EtiTheSpirit** [comment]
Ah yeah, that's right. Will have the fix out soon.

Depending on what I want to do with the release, this could be either 1.1.1 (hotfix update) or 1.2.0 (if I add animator drivers)

**Comment by EtiTheSpirit** [comment]
Alright, the hotfix is released as 1.1.1.
